name: Build & Publish Notebook Controller Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/notebook-controller/**
      - components/common/**
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/notebook-controller/**
      - components/common/**

env:
  DOCKER_USER: adysh97
  IMG: adysh97/notebook-controller

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        #if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

      - name: Run Notebook Controller build
        run: |
          cd components/notebook-controller
          #make docker-build

      - name: Run Notebook Controller push
        #if: github.event_name == 'push'
        run: |
          cd components/notebook-controller
          #make docker-push

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ppc64le

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build multi-arch docker image
        run: |
          cd components/notebook-controller
          make docker-build-multi-arch

      - name: Build  and push multi-arch docker image
        run: |
          cd components/notebook-controller
          make docker-build-push-multi-arch
